"""'init'

Revision ID: 8e544706f351
Revises: 
Create Date: 2023-01-23 14:54:07.439564

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '8e544706f351'  # pylint: disable=C0103
down_revision = None  # pylint: disable=C0103
branch_labels = None  # pylint: disable=C0103
depends_on = None  # pylint: disable=C0103


def upgrade() -> None:
    """
    # ### commands auto generated by Alembic - please adjust! ###
    """
    op.create_table('condition',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(),
                              server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(),
                              server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
                    sa.Column('text', sa.String(length=22), nullable=False),
                    sa.Column('full_text', sa.String(length=50), nullable=False),
                    sa.Column('icon', sa.String(length=20), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('id'),
                    sa.UniqueConstraint('text')
                    )
    op.create_table('user',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(),
                              server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(),
                              server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('id')
                    )
    op.create_table('face',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(),
                              server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(),
                              server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
                    sa.Column('filename', sa.String(length=100), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('id')
                    )
    op.create_index(op.f('ix_face_user_id'), 'face', ['user_id'], unique=False)
    op.create_table('weather',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(),
                              server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(),
                              server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
                    sa.Column('lat', sa.Float(), nullable=False),
                    sa.Column('lon', sa.Float(), nullable=False),
                    sa.Column('temperature', sa.Integer(), nullable=False),
                    sa.Column('feels_like', sa.Integer(), nullable=False),
                    sa.Column('wind_speed', sa.Integer(), nullable=False),
                    sa.Column('wind_gust', sa.Integer(), nullable=False),
                    sa.Column('wind_dir', sa.String(length=2), nullable=False),
                    sa.Column('pressure', sa.Integer(), nullable=False),
                    sa.Column('humidity', sa.Integer(), nullable=False),
                    sa.Column('is_day_time', sa.Boolean(), nullable=False),
                    sa.Column('season', sa.String(length=6), nullable=False),
                    sa.Column('sunrise', sa.Time(), nullable=False),
                    sa.Column('sunset', sa.Time(), nullable=False),
                    sa.Column('week', sa.Integer(), nullable=False),
                    sa.Column('moon', sa.Integer(), nullable=False),
                    sa.Column('condition_text', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(['condition_text'], ['condition.text'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('id')
                    )
    op.create_table('forecast_part',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(),
                              server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(),
                              server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
                    sa.Column('part_name', sa.String(), nullable=False),
                    sa.Column('temp_avg', sa.Integer(), nullable=False),
                    sa.Column('temp_max', sa.Integer(), nullable=False),
                    sa.Column('temp_min', sa.Integer(), nullable=False),
                    sa.Column('feels_like', sa.Integer(), nullable=False),
                    sa.Column('wind_speed', sa.Integer(), nullable=False),
                    sa.Column('wind_gust', sa.Integer(), nullable=False),
                    sa.Column('wind_dir', sa.String(length=2), nullable=False),
                    sa.Column('pressure', sa.Integer(), nullable=False),
                    sa.Column('humidity', sa.Integer(), nullable=False),
                    sa.Column('prec_mm', sa.Integer(), nullable=False),
                    sa.Column('prec_period', sa.Integer(), nullable=False),
                    sa.Column('prec_prob', sa.Integer(), nullable=False),
                    sa.Column('weather_id', sa.Integer(), nullable=False),
                    sa.Column('condition_text', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(['condition_text'], ['condition.text'], ),
                    sa.ForeignKeyConstraint(['weather_id'], ['weather.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    # ### commands auto generated by Alembic - please adjust! ###
    """
    op.drop_table('forecast_part')
    op.drop_table('weather')
    op.drop_index(op.f('ix_face_user_id'), table_name='face')
    op.drop_table('face')
    op.drop_table('user')
    op.drop_table('condition')
    # ### end Alembic commands ###
