name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    # this Action should follow steps to set up Python build environment
    - name: Install Python dependencies
      uses: py-actions/py-dependency-install@v4
      with:
        update-pip: "false"
        update-setuptools: "false"
        update-wheel: "false"
    - name: Install software
      run: |
        apt-get install portaudio19-dev python-pyaudio python3-pyaudio
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
